server:
  port: 7070
spring:
  profiles:
    active: prod
  application:
    name: spring-cloud-basics-backend-hello

logging:
  level:
    org.springframework.security: INFO

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://spring-cloud-registry:8761/eureka/
